version: 2.1
orbs:
  docker: circleci/docker@2.0.1
  aws-eks: circleci/aws-eks@2.1.0
  kubernetes: circleci/kubernetes@1.0

jobs:
  deploy-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
        
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            pwd
            ls -l
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=capstone-Project5 \
              --stack-name "backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
              #exit 1
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            backendip=$(aws ec2 describe-instances \
              --query "Reservations[*].Instances[*].PublicIpAddress" \
              --filters "Name=tag:project,Values=capstone-Project5" \
              --output=text)
            echo $backendip >> .circleci/ansible/machineip.txt
            
  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout
         
      - run:
          name: Ensure front-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=capstone-Project5 \
              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
              #exit 1

  create-and-upload-docker-image:
    machine: true
        
    steps:
      # Checkout code from git
      - checkout

      - run:
          name: Create docker image and upload
          command: |
            dockerpath=inaarya/path
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            pwd
            docker build --tag=capstone .
            docker tag capstone:latest $dockerpath:latest
            docker push $dockerpath:latest
  
  
  create-eks-cluster:
    docker: 
      - image: aws-eks/python3
       
    steps:
      - checkout

      - run:
          command: |
           eksctl create cluster name capstonecluster -f cluster.yml
      
    
  cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout

      - run:
          name: Update cloudfront distribution
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name capstone-Project5-Cloudfront \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=capstone

test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster

workflows:
  default:
    jobs:
      #- deploy-backend
      #- create-and-upload-docker-image  
      - create-eks-cluster
          #requires: [deploy-backend]
      #- deploy-frontend
      #- cloudfront-update
      
      #- test-cluster
