
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.0
  docker: circleci/docker@2.0.1
  kubernetes: circleci/kubernetes@1.0
  python: circleci/python@1.5.0

jobs:
  configure-docker:
    description: Configure Docker environment.
    docker:
      - image: circleci/docker:2.0.1
    steps:
      - run:
          name: Configure docker
          when: on_fail
          command: |
            docker build --tag=captone .
            docker image ls
            docker run -p 8000:80 captone
            #exit 1

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster
workflows:
  default:
    jobs:
      - configure-docker